# roles/openldap/tasks/main.yaml

# ========= Install OpenLDAP packages =========
- name: Install OpenLDAP server and client packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop:
  - openldap
  - openldap-servers
  - openldap-clients

# ========= Ensure slapd service is enabled and running =========
- name: Ensure slapd is enabled and running
  ansible.builtin.service:
    name: slapd
    state: started
    enabled: yes

# ========= Deploy DB_CONFIG =========
- name: Deploy DB_CONFIG
  ansible.builtin.copy:
    src: DB_CONFIG
    dest: /var/lib/ldap/DB_CONFIG
    owner: ldap
    group: ldap
    mode: '0644'

# ========= Ensure correct permissions on /var/lib/ldap =========
- name: Fix ownership of LDAP database directory
  ansible.builtin.file:
    path: /var/lib/ldap
    owner: ldap
    group: ldap
    recurse: yes

# ========= Configure rootDN (cn=Manager) =========
- name: Render configure-rootdn.ldif
  ansible.builtin.template:
    src: configure-rootdn.ldif.j2
    dest: /tmp/configure-rootdn.ldif

- name: Apply configure-rootdn.ldif
  ansible.builtin.command:
    cmd: ldapmodify -Y EXTERNAL -H ldapi:/// -f /tmp/configure-rootdn.ldif
  register: rootdn_config
  changed_when: "'modifying' in rootdn_config.stdout or 'adding' in rootdn_config.stdout"

# ========= Add baseDN and Manager entry =========
- name: Render baseDN LDIF
  ansible.builtin.template:
    src: basedn.ldif.j2
    dest: /tmp/basedn.ldif

- name: Add baseDN entry to LDAP
  ansible.builtin.command:
    cmd: ldapadd -x -D "{{ ldap_rootdn }}" -w "{{ ldap_rootpw }}" -H ldap://localhost -f /tmp/basedn.ldif
  register: basedn_add
  failed_when: basedn_add.rc not in [0, 68]  # 68 = Already exists
  changed_when: basedn_add.rc == 0
