- name: Install OpenLDAP
  ansible.builtin.package:
    name:
      - openldap-servers
      - openldap-clients
    state: present

- name: Start and enable slapd
  ansible.builtin.service:
    name: slapd
    state: started
    enabled: yes

- name: Generate hashed LDAP root password
  ansible.builtin.command: slappasswd -s {{ ldap_rootpw }}
  register: rootpw_hash
  changed_when: false

- name: Render LDIF for suffix and rootDN
  ansible.builtin.template:
    src: configure-rootdn.ldif.j2
    dest: /tmp/configure-rootdn.ldif
    owner: root
    group: root
    mode: '0600'

- name: Apply LDAP rootDN and suffix config
  ansible.builtin.command: ldapmodify -Y EXTERNAL -H ldapi:/// -f /tmp/configure-rootdn.ldif
  args:
    creates: /etc/openldap/slapd.d/olcRootPW.set
  notify: Restart slapd

- name: Create marker file to avoid reapplying rootDN config
  ansible.builtin.file:
    path: /etc/openldap/slapd.d/olcRootPW.set
    state: touch

# -----------------------------
# Kerberos schema handling
# -----------------------------
- block:
    - name: Check if system already has kerberos.ldif
      ansible.builtin.stat:
        path: /usr/share/openldap/schema/kerberos.ldif
      register: kerberos_ldif

    - name: Copy kerberos.ldif if available
      ansible.builtin.command:
        cmd: ldapadd -Y EXTERNAL -H ldapi:/// -f /usr/share/openldap/schema/kerberos.ldif
      when: kerberos_ldif.stat.exists
      args:
        creates: /etc/openldap/slapd.d/cn=config/cn=schema/cn={0}kerberos.ldif
      notify: Restart slapd

    - name: Create minimal slapd.conf for kerberos schema
      ansible.builtin.template:
        src: kerberos_convert.conf.j2
        dest: /tmp/kerberos_convert.conf
      when: not kerberos_ldif.stat.exists

    - name: Convert kerberos.schema to LDIF
      ansible.builtin.command:
        cmd: slaptest -f /tmp/kerberos_convert.conf -F /tmp/kerberos_schema
      when: not kerberos_ldif.stat.exists
      args:
        creates: /tmp/kerberos_schema/cn=config/cn=schema/cn={0}kerberos.ldif

    - name: Add kerberos schema to slapd
      ansible.builtin.command:
        cmd: ldapadd -Y EXTERNAL -H ldapi:/// -f /tmp/kerberos_schema/cn=config/cn=schema/cn={0}kerberos.ldif
      when: not kerberos_ldif.stat.exists
      args:
        creates: /etc/openldap/slapd.d/cn=config/cn=schema/cn={0}kerberos.ldif
      notify: Restart slapd

  always:
    - name: Cleanup temporary kerberos schema files
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop:
        - /tmp/kerberos_convert.conf
        - /tmp/kerberos_schema
