# roles/openldap/tasks/main.yaml

# ========= Install OpenLDAP packages =========
- name: Install OpenLDAP server and client packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop:
  - openldap
  - openldap-servers
  - openldap-clients

# ========= Ensure slapd is enabled and running =========
- name: Ensure slapd is enabled and running
  ansible.builtin.service:
    name: slapd
    state: started
    enabled: yes

# ========= Deploy DB_CONFIG =========
- name: Deploy DB_CONFIG
  ansible.builtin.copy:
    src: DB_CONFIG
    dest: /var/lib/ldap/DB_CONFIG
    owner: ldap
    group: ldap
    mode: '0644'

# ========= Set ownership of /var/lib/ldap =========
- name: Set ownership for LDAP database directory
  ansible.builtin.file:
    path: /var/lib/ldap
    state: directory
    owner: ldap
    group: ldap
    recurse: yes

# ========= Render baseDN LDIF =========
- name: Render baseDN LDIF (for debugging / backup)
  ansible.builtin.template:
    src: basedn.ldif.j2
    dest: /tmp/basedn.ldif
    mode: '0600'

# ========= Add baseDN entry =========
- name: Add baseDN entry to LDAP
  ansible.builtin.command:
    cmd: ldapadd -x -D "{{ ldap_rootdn }}" -w "{{ ldap_rootpw }}" -H ldap://localhost -f /tmp/basedn.ldif
  register: add_basedn
  failed_when:
    - add_basedn.rc != 0
    - '"already exists" not in add_basedn.stderr'
  changed_when: "'already exists' not in add_basedn.stderr"

# ========= Verify baseDN =========
- name: Verify baseDN exists
  ansible.builtin.command:
    cmd: ldapsearch -x -b "{{ basedn }}" -H ldap://localhost
  register: verify_basedn
  changed_when: false
