---
# OpenLDAP Role - Tasks

- name: Install OpenLDAP packages
  ansible.builtin.package:
    name:
      - openldap-servers
      - openldap-clients
    state: present

- name: Start and enable slapd
  ansible.builtin.service:
    name: slapd
    state: started
    enabled: yes

# --------------------------------------------------------------------
# LDAP root password setup
# --------------------------------------------------------------------
- name: Generate hashed LDAP root password
  ansible.builtin.command: slappasswd -s {{ ldap_rootpw }}
  register: rootpw_hash
  changed_when: false

- name: Render LDIF for suffix and rootDN
  ansible.builtin.template:
    src: configure-rootdn.ldif.j2
    dest: /tmp/configure-rootdn.ldif
    owner: root
    group: root
    mode: '0600'

- name: Apply LDAP rootDN and suffix config
  ansible.builtin.command: ldapmodify -Y EXTERNAL -H ldapi:/// -f /tmp/configure-rootdn.ldif
  args:
    creates: /etc/openldap/slapd.d/olcRootPW.set

- name: Create marker file to avoid reapplying rootDN config
  ansible.builtin.file:
    path: /etc/openldap/slapd.d/olcRootPW.set
    state: touch

# --------------------------------------------------------------------
# Kerberos schema setup
# --------------------------------------------------------------------
- name: Copy Kerberos schema into place
  ansible.builtin.copy:
    src: kerberos.schema
    dest: /etc/openldap/schema/kerberos.schema
    owner: root
    group: root
    mode: '0644'

- name: Convert Kerberos schema to LDIF
  ansible.builtin.command: >
    slaptest -f /etc/openldap/schema/kerberos.schema -F /tmp/kerberos_schema
  args:
    creates: /tmp/kerberos_schema/cn=config/cn=schema/cn={0}kerberos.ldif

- name: Add Kerberos schema to slapd
  ansible.builtin.command: >
    ldapadd -Y EXTERNAL -H ldapi:/// -f /tmp/kerberos_schema/cn=config/cn=schema/cn={0}kerberos.ldif
  args:
    creates: /etc/openldap/slapd.d/cn=config/cn=schema/cn={0}kerberos.ldif

# --------------------------------------------------------------------
# Base DN creation
# --------------------------------------------------------------------
- name: Render LDIF for baseDN
  ansible.builtin.template:
    src: basedn.ldif.j2
    dest: /tmp/basedn.ldif
    owner: root
    group: root
    mode: '0600'

- name: Add baseDN entry
  ansible.builtin.command: >
    ldapadd -x -D {{ ldap_rootdn }} -w {{ ldap_rootpw }} -f /tmp/basedn.ldif
  args:
    creates: /etc/openldap/slapd.d/basedn.set

- name: Create marker file for baseDN
  ansible.builtin.file:
    path: /etc/openldap/slapd.d/basedn.set
    state: touch
