# roles/kerberos/tasks/main.yaml

# ========= Install Kerberos packages =========
- name: Install Kerberos packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop:
    - krb5-server
    - krb5-server-ldap
    - krb5-libs
    - krb5-workstation
    - openldap-clients
    - python-ldap
    - python3-pexpect

# ========= Deploy kdc.conf =========
- name: Deploy kdc.conf
  ansible.builtin.template:
    src: kdc.conf.j2
    dest: /var/kerberos/krb5kdc/kdc.conf
    owner: root
    group: root
    mode: '0644'

# ========= Deploy kadm5.acl =========
- name: Deploy kadm5.acl
  ansible.builtin.template:
    src: kadm5.acl.j2
    dest: /var/kerberos/krb5kdc/kadm5.acl
    owner: root
    group: root
    mode: '0600'
  notify:
    - Restart kadmin

# ========= Create Kerberos container in LDAP =========
- name: Create Kerberos container in LDAP
  ansible.builtin.command:
    cmd: ldapadd -x -D "{{ ldap_rootdn }}" -w "{{ ldap_rootpw }}" -H ldap://localhost -f /tmp/kerberos-container.ldif
  args:
    creates: "/tmp/kerberos-container.done"
  register: add_container
  failed_when:
    - add_container.rc != 0
    - '"already exists" not in add_container.stderr'
  changed_when: "'already exists' not in add_container.stderr"

- name: Mark Kerberos container created
  ansible.builtin.file:
    path: /tmp/kerberos-container.done
    state: touch

# ========= Create Kerberos service account in LDAP =========
- name: Create Kerberos service account
  ansible.builtin.command:
    cmd: ldapadd -x -D "{{ ldap_rootdn }}" -w "{{ ldap_rootpw }}" -H ldap://localhost -f /tmp/kerberos-service.ldif
  args:
    creates: "/tmp/kerberos-service.done"
  register: add_service
  failed_when:
    - add_service.rc != 0
    - '"already exists" not in add_service.stderr'
  changed_when: "'already exists' not in add_service.stderr"

- name: Mark Kerberos service account created
  ansible.builtin.file:
    path: /tmp/kerberos-service.done
    state: touch

# ========= Generate service.keyfile for LDAP backend =========
- name: Generate service.keyfile
  ansible.builtin.command:
    cmd: kdb5_ldap_util stashsrvpw -f {{ kerberos_service_keyfile }} "{{ kerberos_service_dn }}"
  args:
    creates: "{{ kerberos_service_keyfile }}"

# ========= Initialize Kerberos database with LDAP backend =========
- name: Initialize Kerberos database
  ansible.builtin.command:
    cmd: kdb5_util create -r {{ kerberos_realm }} -s
  register: kdb_init
  failed_when:
    - kdb_init.rc != 0
    - '"already exists" not in kdb_init.stderr'
  changed_when: "'already exists' not in kdb_init.stderr"


# ========= Deploy kdc.conf =========
- name: Deploy kdc.conf
  ansible.builtin.template:
    src: kdc.conf.j2
    dest: /var/kerberos/krb5kdc/kdc.conf
    owner: root
    group: root
    mode: '0644'
  notify:
    - Restart krb5kdc
    - Restart kadmin
