- name: Install Kerberos packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop:
  - krb5-server
  - krb5-libs
  - krb5-workstation
  - openldap-clients

- name: Deploy krb5.conf
  ansible.builtin.template:
    src: krb5.conf.j2
    dest: /etc/krb5.conf
    owner: root
    group: root
    mode: "0644"

- name: Deploy kdc.conf
  ansible.builtin.template:
    src: kdc.conf.j2
    dest: /var/kerberos/krb5kdc/kdc.conf
    owner: root
    group: root
    mode: "0644"

- name: Ensure Kerberos subtree exists in LDAP
  ansible.builtin.template:
    src: kerberos-subtree.ldif.j2
    dest: /tmp/kerberos-subtree.ldif
    owner: root
    group: root
    mode: "0600"

- name: Add Kerberos subtree and service account to LDAP
  ansible.builtin.command: >
    ldapadd -x -D "{{ ldap_rootdn }}" -w "{{ ldap_rootpw }}" -f /tmp/kerberos-subtree.ldif
  args:
    creates: /var/kerberos/krb5kdc/kerberos-subtree.set

- name: Create marker file for Kerberos subtree
  ansible.builtin.file:
    path: /var/kerberos/krb5kdc/kerberos-subtree.set
    state: touch

- name: Create Kerberos database with LDAP backend
  ansible.builtin.command: >
    kdb5_ldap_util -D "{{ ldap_rootdn }}" -w "{{ ldap_rootpw }}"
    create -subtrees "{{ krb_subtree }}" -r "{{ realm }}" -s
  args:
    creates: /var/kerberos/krb5kdc/.k5.{{ realm }}

- name: Set KDC LDAP service password
  ansible.builtin.command: >
    kdb5_ldap_util -D "{{ ldap_rootdn }}" -w "{{ ldap_rootpw }}"
    stashsrvpw -f /var/kerberos/krb5kdc/ldap.stash "{{ kdc_ldap_dn }}"
  args:
    creates: /var/kerberos/krb5kdc/ldap.stash

- name: Enable and start krb5kdc
  ansible.builtin.service:
    name: krb5kdc
    state: started
    enabled: yes
  notify: Restart krb5kdc

- name: Enable and start kadmin
  ansible.builtin.service:
    name: kadmin
    state: started
    enabled: yes
  notify: Restart kadmin
