---
# Kerberos role tasks

- name: Install Kerberos packages
  package:
    name: "{{ item }}"
    state: present
  loop: "{{ kerberos_packages }}"

# --- LDAP Container for Kerberos ---
- name: Ensure kerberos templates directory exists (tmp)
  file:
    path: /tmp
    state: directory
    mode: '0755'

- name: Render kerberos container LDIF
  template:
    src: kerberos-container.ldif.j2
    dest: /tmp/kerberos-container.ldif

- name: Create Kerberos container in LDAP
  command: ldapadd -x -D "cn=Manager,{{ ldap_basedn }}" -w "{{ ldap_admin_pw }}" -H ldap://localhost -f /tmp/kerberos-container.ldif
  register: add_container
  failed_when: add_container.rc != 0 and "Already exists" not in add_container.stderr

# --- Kerberos Service Account ---
- name: Render kerberos service account LDIF
  template:
    src: kerberos-service.ldif.j2
    dest: /tmp/kerberos-service.ldif

- name: Create Kerberos service account in LDAP
  command: ldapadd -x -D "cn=Manager,{{ ldap_basedn }}" -w "{{ ldap_admin_pw }}" -H ldap://localhost -f /tmp/kerberos-service.ldif
  register: add_service
  failed_when: add_service.rc != 0 and "Already exists" not in add_service.stderr

# --- Service Keyfile ---
- name: Ensure Kerberos keyfile directory exists
  file:
    path: "{{ kerberos_db_dir }}"
    state: directory
    mode: '0700'

- name: Create service.keyfile (one-line format)
  copy:
    dest: "{{ kerberos_db_dir }}/service.keyfile"
    content: "{{ krb_svc_dn }} {{ krb_svc_pw }}\n"
    owner: root
    group: root
    mode: '0600'

- name: Verify service.keyfile contents
  command: cat "{{ kerberos_db_dir }}/service.keyfile"
  register: keyfile_content

- debug:
    msg: "Service keyfile contains: {{ keyfile_content.stdout }}"

# --- Configurations ---
- name: Deploy kdc.conf
  template:
    src: kdc.conf.j2
    dest: /var/kerberos/krb5kdc/kdc.conf
    owner: root
    group: root
    mode: '0644'

- name: Deploy kadm5.acl
  template:
    src: kadm5.acl.j2
    dest: /var/kerberos/krb5kdc/kadm5.acl
    owner: root
    group: root
    mode: '0644'

# --- KDC Database ---
- name: Check for Kerberos DB marker file
  stat:
    path: "{{ kerberos_db_dir }}/principal.ok"
  register: kerberos_db_marker

- name: Create Kerberos database with LDAP backend (non-interactive)
  command: kdb5_util create -r {{ kerberos_realm }} -s
  environment:
    KRB5_KDC_PROFILE: /var/kerberos/krb5kdc/kdc.conf
  when: not kerberos_db_marker.stat.exists

- name: Mark Kerberos DB as created
  file:
    path: "{{ kerberos_db_dir }}/principal.ok"
    state: touch
  when: not kerberos_db_marker.stat.exists
