# - name: Restart krb5kdc
#   ansible.builtin.service:
#     name: krb5kdc
#     state: restarted

# - name: Restart kadmin
#   ansible.builtin.service:
#     name: kadmin
#     state: restarted

- name: Restart Kerberos services
  ansible.builtin.service:
    name: "{{ item }}"
    state: restarted
  loop:
    - krb5kdc
    - kadmin
